import { View, Text, StyleSheet, SafeAreaView, FlatList, ScrollView ,Dimensions} from 'react-native';
import React from 'react';

const Privacy = () => {
    const privacydata = [
        {
            id: 1,
            title: 'Account',
            description: 'means a unique account created for You to access our Service or parts of our Service.'
        },
        {
            id: 2,
            title: 'Affiliate',
            description: 'means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.'
        },
        {
            id: 3,
            title: 'Application',
            description: 'refers to e-Nirikshak, the software program provided by the Company.'
        },
        {
            id: 4,
            title: 'Company',
            description: '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Sharda University, plot no 32, 34, Knowledge Park III, Greater Noida, Ruhallapur, Uttar Pradesh 201310.'
        },
        {
            id: 5,
            title: 'Country',
            description: 'refers to: Uttar Pradesh, India.'
        },
        {
            id: 6,
            title: 'Device',
            description: 'means any device that can access the Service such as a computer, a cellphone or a digital tablet.'
        },
        {
            id: 7,
            title: 'Personal Data',
            description: 'is any information that relates to an identified or identifiable individual.'
        },
        {
            id: 8,
            title: 'Service',
            description: 'refers to the Application.'
        },
        {
            id: 9,
            title: 'Service Provider',
            description: 'means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.'
        },
        {
            id: 10,
            title: 'Usage Data',
            description: 'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).'
        },
        {
            id: 11,
            title: 'You',
            description: 'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.'
        },
    ];
    const { width, height } = Dimensions.get('window');
    const isMobile = width < 768; 
   
    const personaldata=[
        {
            id:1,
            name:'Email address'
        },
        {
            id:2,
            name:'First name and last name'
        },
        {
            id:3,
            name:'Phone number'
        },

        {
            id:4,
            name:'Address, State, Province, ZIP/Postal code, City'
        },
        {
            id:5,
            name:'Usage Data'
        }
        

    ];
    const usagedata=[
     {
         id:1,
         para:'Usage Data is collected automatically when using the Service.'
     },
 
    {
        id: 2,
        para: "Usage Data may include information such as Your Device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data."
    },
    
    {
     id:3,
     para:'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.'

    },
    {
        id:4,
        para:'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.'
    }

    ]
    
    const renderItem = ({ item }) => (
        <View style={styles.item}>
            <Text style={styles.listheading}>• {item.title}</Text>
            <Text style={styles.description}>{item.description}</Text>
        </View>
    );
    const persenaldataitems = ({ item }) => (
        <View style={styles.item}>
            <Text style={styles.description}>• {item.name}</Text>
            
        </View>
    );
    const usagedataitems = ({ item }) => (
        <View style={styles.item}>
            <Text style={styles.description}> {item.para}</Text>
            
        </View>
    );
    const yourpersonaldataitem = ({ item }) => (
        <View style={styles.item}>
            <Text style={styles.listheading}>• {item.title}</Text>
            <Text style={styles.description}>{item.description}</Text>
        </View>
    );
    
    return (
        <SafeAreaView style={styles.container}>
            <ScrollView>
                <View style={styles.formContainer}>

                    <Text style={styles.heading}>Privacy Policy</Text>

                    <Text style={styles.text}>
                        Sharda University operates the website https://examination.sharda.ac.in/e-Nirikshak and the corresponding mobile application.
                    </Text>

                    <Text style={styles.text}>
                        This page informs you of our policies regarding the collection, use and disclosure of Personal Information we receive from users of our e-Nirikshak product.
                    </Text>

                    <Text style={styles.subheading}>Information Collection And Use</Text>
                    <Text style={styles.text}>
                        While using our website, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to your Name, Email Address, Phone Numbers & Address.
                    </Text>

                    <Text style={styles.subheading}>Log Data</Text>

                    <Text style={styles.text}>
                        Like most website operators, e-Nirikshak collects information that your browser sends whenever you visit our website.
                    </Text>

                    <Text style={styles.text}>
                        This Log Data may include information such as your computer's Internet Protocol ("IP") address, browser type, browser version, the pages of our Site that you visit, the time and date of your visit, the time spent on those pages and other statistics.
                    </Text>

                    <Text style={styles.text}>
                        In addition, we may use third party services such as Google Analytics that collect, monitor and analyze this information.
                    </Text>
                
                    <Text style={styles.subheading}>Communications</Text>

                    <Text style={styles.text}>
                        We may use your Personal Information to contact you through emails, newsletters and telephonic support. This may be used to share marketing or promotional materials and other product related information such as new feature announcement etc.
                    </Text>

                    <Text style={styles.subheading}>Cookies</Text>

                    <Text style={styles.text}>
                        Cookies are files with small amount of data, which may include an anonymous unique identifier. Cookies are sent to your browser from a web site and stored on your computer's hard drive.
                    </Text>

                    <Text style={styles.text}>
                    Like many other websites, we use "cookies" to collect information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our website to their full potential.
                    </Text>

                    <Text style={styles.subheading}>Security</Text>

                    <Text style={styles.text}>
                        The security of your Personal Information is important to us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.
                    </Text>

                    <Text style={styles.subheading}>Changes To This Privacy Policy</Text>

                    {/* <Text style={styles.text}>
                        This Privacy Policy is effective as of (27/08/2019) and will remain in effect except with respect to any changes in its provisions in the future, which will be in effect immediately after being posted on this page.
                    </Text> */}

                    <Text style={styles.text}>
                        We reserve the right to update or change our Privacy Policy at any time and you should check this Privacy Policy periodically. Your continued use of the Service after we post any modifications to the Privacy Policy on this page will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy.
                    </Text>

                    {/* <Text style={styles.text}>
                        If we make any material changes to this Privacy Policy, we will notify you either through the email address you have provided us, or by placing a prominent notice on our website.
                    </Text> */}

                </View>
            </ScrollView>
        </SafeAreaView>
    );
};

export default Privacy;

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    formContainer: {
        marginBottom: 20,
        padding: 20,
        backgroundColor: '#fff',
        marginHorizontal: 15,
        marginVertical: 10,
        borderRadius: 10,
        // shadowColor: '#000',
        // shadowOpacity: 0.1,
        // shadowRadius: 10,
        // shadowOffset: { width: 0, height: 5 },
        // elevation: 5,
    },
    heading: {
        fontSize: 20,
        fontWeight: '700',
        marginVertical: 10,
        color: '#333',
    },
    updateDate: {
        fontSize: 14,
        color: '#666',
        marginBottom: 15,
    },
    subheading: {
        fontSize: 18,
        fontWeight: '600',
        marginVertical: 5,
        color: '#444',
    },
    subheadingchild: {
        fontSize: 16,
        fontWeight: '600',
        marginVertical: 5,
        color: '#555',
    },
    text: {
        fontSize: 16,
        color: '#666',
        lineHeight: 24,
        marginBottom: 15,
    },
    listheading: {
        fontSize: 16,
        fontWeight: '700',
        color: '#444',
        marginRight: 5, 
    },
    item: {
        flexDirection: 'row', 
        alignItems: 'flex-start', 
        marginBottom: 10, 
    },
    description: {
        flex: 1,  
        fontSize: 16,
        color: '#666',
        lineHeight: 24,
    },
    link: {
        color: '#1E90FF',
        textDecorationLine: 'underline',
    },
});
